sudo: false
language: c  # Choose a lightweight base image

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp3-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- stack setup
- stack --no-terminal test
